server:
  port: 8001

spring:
  application:
    name: cloud-account
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.106.160:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.106.160:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: shortLink

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

sms:
  access-key-id: LTAI5tH16buiu8BxJ6uHactv
  access-key-secret: YGVEwhbxinAlo3u9Mxz5F2O9vw1iqU
  region: cn-qingdao
  endpoint: dysmsapi.aliyuncs.com
  sign-name: 乐优商城
  template-code: SMS_206561965
  template-param: '{"code":"%s"}'

