server:
  port: 8001

spring:
  application:
    name: cloud-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.106.160:8848
        username: nacos
        password: nacos
  rabbitmq:
    host: 47.104.106.160
    port: 5672
    virtual-host: dev
    username: admin
    password: shortLink
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.104.106.160:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: shortLink
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          max-lifetime: 1800000
          minimum-idle: 5
          maximum-pool-size: 50
    props:
      sql:
        show: true

    sharding:
      tables:
        traffic:
          actual-data-nodes: ds0.traffic_$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: traffic_$->{ account_no % 2 }
              sharding-column: account_no
          key-generator:
            type: SNOWFLAKE
            column: id
            props:
              worker:
                id: ${workId}
  redis:
    client-type: jedis
    host: 47.104.106.160
    password: shortLink
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 100
        max-wait: 6000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

sms:
  access-key-id: LTAI5tH16buiu8BxJ6uHactv
  access-key-secret: YGVEwhbxinAlo3u9Mxz5F2O9vw1iqU
  region: cn-qingdao
  endpoint: dysmsapi.aliyuncs.com
  sign-name: 乐优商城
  template-code: SMS_206561965
  template-param: '{"code":"%s"}'
aliyun:
  oss:
    bucket-name: short-link-cloud
    endpoint: oss-cn-qingdao.aliyuncs.com
    access-key-id: LTAI5t8N2UQL1b6jAT3GTqHg
    access-key-secret: UnXHx4uPYqthruSFmNqjG7ZEIspJAX

