server:
  port: 8005

spring:
  application:
    name: cloud-link-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.106.160:8848
        username: nacos
        password: nacos
  redis:
    client-type: jedis
    host: 47.104.106.160
    password: shortLink
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 100
        max-wait: 60000
  rabbitmq:
    host: 47.104.106.160
    port: 5672
    virtual-host: dev
    username: admin
    password: shortLink
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.104.106.160:3306/cloud_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: shortLink
        type: com.zaxxer.hikari.HikariDataSource
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: ds0
      default-key-generator:
        type: SNOWFLAKE
        column: id
        props:
          worker:
            id: ${workId}
      tables:
        # 水平分表
        product_order:
          actual-data-nodes: ds0.product_order_$->{0..1}
          table-strategy:
            inline:
              sharding-column: account_no
              algorithm-expression: product_order_$->{account_no % 2}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

pay:
  wechat:
    mch-id: 1558950191
    wx-pay-appid: wx74862e0dfcf69954
    mch-serial-no: 34345964330B66427E0D3D28826C4993C77E631F
    api-v3-key: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
    private-key-path: classpath:/cert/apiclient_key.pem
    success-return-url: https://www.baidu.com
    callback-url: https://2l818y5997.zicp.fun/api/callback/order/v1/wechat






