server:
  port: 8003

spring:
  application:
    name: cloud-link-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.106.160:8848
        username: nacos
        password: nacos
  redis:
    client-type: jedis
    host: 47.104.106.160
    password: shortLink
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 100
        max-wait: 60000
  shardingsphere:
    datasource:
      names: ds0,ds1,dsa
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.104.106.160:3306/cloud_link_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: shortLink
        type: com.zaxxer.hikari.HikariDataSource
      ds1:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.104.106.160:3306/cloud_link_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: shortLink
        type: com.zaxxer.hikari.HikariDataSource
      dsa:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.104.106.160:3306/cloud_link_a?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: shortLink
        type: com.zaxxer.hikari.HikariDataSource
    props:
      sql:
        show: true
    sharding:
      tables:
        # 水平分库，行表达式
        link_group:
          database-strategy:
            inline:
              sharding-column: account_no
              algorithm-expression: ds$->{account_no % 2}
        # 水平分库分表，自定义路由策略
        short_link:
          database-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.starry.strategy.CustomDBPreciseShardingAlgorithm
          actual-data-nodes: ds0.short_link,ds1.short_link,dsa.short_link
          table-strategy:
            standard:
              sharding-column: code
              precise-algorithm-class-name: com.starry.strategy.CustomTablePreciseShardingAlgorithm
        # 水平分库分表，行表达式
        group_code_mapping:
          database-strategy:
            inline:
              sharding-column: account_no
              algorithm-expression: ds$->{account_no % 2}
          actual-data-nodes: ds$->{0..1}.group_code_mapping_$->{0..1}
          table-strategy:
            inline:
              sharding-column: group_id
              algorithm-expression: group_code_mapping_$->{group_id % 2}

      default-data-source-name: ds0
      default-key-generator:
        type: SNOWFLAKE
        column: id
        props:
          worker:
            id: ${workId}
  rabbitmq:
    host: 47.104.106.160
    port: 5672
    virtual-host: dev
    username: admin
    password: shortLink
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

